### PR TITLE
fix(content): #210 show real bookmark ui in ActivityFeed

### LINKED ISSUE #210: Add real bookmarks UI on ActivityFeed
Stars should show up for bookmarked items only

### PR DESCRIPTION
**Pull request by k88hudson**
I need to update this after https://github.com/mozilla/activity-streams/pull/208 lands

Fixes #210

### CODE REVIEW

**Comment by pdehaan** [comment]
Looks fantastic! It seems to enable/disable correctly if I remove the bookmark.
Only oddity I noticed is that when you mouse-over the bookmark star icon, it switches to an i-beam cursor like it's trying to select text. Not sure which cursor is best in this case though (presumably just the standard non-text cursor &mdash; `cursor: default;` on the [`&.bookmark::after`](https://github.com/mozilla/activity-streams/pull/211/files#diff-74c812b8c086428c4833cff0b44c4ed7R55) selector): https://css-tricks.com/almanac/properties/c/cursor/
But that may not be important if we're moving towards the ability to click on the star/circle to bookmark or unbookmark items.

new_tab

**Comment by k88hudson** [comment]
Ok, all rebased!

**Comment by k88hudson** [comment]
R? @rlr or @pdehaan?

**Comment by pdehaan** [comment]
:+1:

**Pull request merged**
