### PR TITLE
feat(content): #607 UI for real blocking

### PR DESCRIPTION
**Pull request by k88hudson**
- Blocked model removed from reducers, tests updated
- new "Settings Menu" on New Tab
- also adds event listeners for block events in lib/ActivityStreams.js

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/617)

### CODE REVIEW

**Comment by k88hudson** [comment]
I added a follow-up in https://github.com/mozilla/activity-streams/issues/618 for UI to show after unblocking, since this ticket was getting a bit on the big side.

**Comment by k88hudson** [comment]
R? @rlr

**Comment by rlr** [comment]
code looks good to me! I'm gonna play with it a little locally

**Comment by rlr** [comment]
works just as I expect it to. R+! 🚀

**Pull request merged**
