### PR TITLE
chore(update.rdf): Move update.rdf into /dist/ so it is gitignored

### LINKED ISSUE #276: Orphaned @activity-streams-{version}.update.rdf left in root dir after npm run package
Saw this the other day and lazily forgot to file it...
### Steps to reproduce:
1. `$ git status` (should be clean)
2. `$ npm run package`
3. `$ git status`
### Actual results:

A new file, `@activity-streams-1.0.2.update.rdf` is left in my root directory (adjacent to /package.json):

``` sh
$ git status
On branch master
Your branch is ahead of 'origin/master' by 193 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean


$ npm run package
...
JPM [info] Starting jpm xpi on activity-streams-experiment
JPM [info] updateRDF created at /Users/pdehaan/dev/github/activity-streams/@activity-streams-1.0.2.update.rdf
JPM [info] Successfully created XPI at /Users/pdehaan/dev/github/activity-streams/@activity-streams-1.0.2.xpi (4735ms)


$ git status
On branch master
Your branch is ahead of 'origin/master' by 193 commits.
  (use "git push" to publish your local commits)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

    @activity-streams-1.0.2.update.rdf
```
### Expected results:

We should add that pattern to to the /.gitignore, or maybe move the file into /dist/ which is already ignored by our current .gitignore rules.

I imagine it's easiest to just move it into /dist/ at the same time as we move the @activity-streams-{version}.xpi` file (in package.json):

``` js
"package": "npm run bundle && jpm xpi && mv @activity-streams-$npm_package_version.xpi dist/activity-streams-$npm_package_version.xpi"
```

Maybe just do something like append this to the previous "package" script:

``` sh
.. && mv @activity-streams-$npm_package_version.update.rdf dist/update.rdf
```

### PR DESCRIPTION
**Pull request by pdehaan**
r? @oyiptong 

Fixes #276

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/277)

### CODE REVIEW

**Comment by oyiptong** [comment]
I'm inclined to get rid of the package script altogether. Do we use `npm run package` ever?

**Comment by oyiptong** [comment]
The current deployment script runs `jpm sign` which creates an xpi then sends it to AMO for signing: https://github.com/mozilla/activity-streams/blob/5f6bfdeabe607e8b538ef3d5268691e1ed826692/fabfile.py#L32

**Comment by pdehaan** [comment]
> Do we use `npm run package` ever?

Your fabfile currently uses it: [/fabfile.py:31](https://github.com/mozilla/activity-streams/blob/0c1ce94335080a5dbcc8e7fbce7bde01cd81bbd4/fabfile.py#L31), `local("npm run package")`

**Comment by oyiptong** [comment]
Yes, we could also move the packaging task to the fabfile and handle the rdf there

**Comment by oyiptong** [comment]
Given the comments in https://github.com/mozilla/testpilot/issues/406, it looks like we'll be keeping the local signing here, at least for a little while.

If there's no other use for `npm run package`, how about we move the command to fabric and let the fabric script move the url?

**Comment by oyiptong** [comment]
On the other hand, what we could do is get npm scripts to handle the signing task and let the fabric script only be concerned with dealing with S3.

To make that work, you'd need to pass the credentials to the npm script, perhaps via environment variables?

**Comment by pdehaan** [comment]
CLosing for now.

**Pull request closed without merging**
