### PR TITLE
Closes #204 - Unify timestamps across PlacesProvider queries and tests

### LINKED ISSUE #204: Unify timestamps across PlacesProvider queries and tests
FX keeps dates in microseconds, but PlacesProvider and corresponding tests insert/retrieve timestamps in milliseconds.  Some of the queries retrieve some dates and convert them into milliseconds and some do not....  So, this mess needs a cleanup and unification

### PR DESCRIPTION
**Pull request by mzhilyaev**
Fixes #204

### CODE REVIEW

**Comment by oyiptong** [comment]
Can we also have a commit for the front-end code that uses this timestamp?

**Comment by k88hudson** [comment]
@mzhilyaev line is here https://github.com/mozilla/activity-streams/blob/master/content-src/components/ActivityFeed/ActivityFeed.js#L61

**Comment by pdehaan** [comment]
... and probably, [./content-src/components/ActivityFeed/ActivityFeed.js:21](https://github.com/mozilla/activity-streams/blob/a5d66a8bedfe977942212ab6d65e25aa50928265/content-src/components/ActivityFeed/ActivityFeed.js#L21):
```js
<div>{site.lastVisitDate && moment(site.lastVisitDate / 1000).format("h:mma")}</div>
```

**Comment by k88hudson** [comment]
R+, thanks!

**Pull request merged**
