### PR TITLE
fix(content): #592 Change date format for headers

### LINKED ISSUE #592: Update date labels to be more human readable
This is for Activity Feed

### PR DESCRIPTION
**Pull request by k88hudson**
Fixes #592 

This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/593)

### CODE REVIEW

**Comment by pdehaan** [comment]
Looks like this:

activity_stream

**Comment by k88hudson** [comment]
@rlr R?

**Comment by rlr** [comment]
oh this again. We've iterated quite a bit on it 😆

**Comment by rlr** [comment]
hot 🔥 R+

**Comment by k88hudson** [comment]
haha yep ^_^

**Pull request merged**
