### PR TITLE
style(content): #545 Add favicon for newtab

### LINKED ISSUE #545: New Tab, and Activity Stream should have different Tab icons
pasted_image_4_20_16__9_57_pm

We're overusing the activity stream icon.

### PR DESCRIPTION
**Pull request by k88hudson**
This adds a favicon switching function so that new tab/activity stream can have different favicons

Fixes #545 

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/550)

### CODE REVIEW

**Comment by k88hudson** [comment]
@rlr R?

**Comment by rlr** [comment]
WFM! R+

**Comment by pdehaan** [comment]
Semi-related, but I found this to be pretty cool: https://github.com/nfl/react-helmet
You may be able to simplify it down to something similar to this in NewTabPage and TimelinePage:

```html
<Helmet link={[{
    "rel": "icon",
    "type": "image/svg+xml",
    "href": "${options.baseUrl}img/glyph-activityStream-16.svg"
  }]} />
```

(At the obvious expense of yet another dependency)

**Comment by k88hudson** [comment]
@pdehaan not a bad idea, another thing I was thinking about was putting this right into the router. At this point however, i don't think it's really worth it since the complexity level is pretty low

I will file a post-v1 follow-up for consideration though 👍

**Pull request merged**
