### PR TITLE
chore(debugger): Added ui component and data source tester

### PR DESCRIPTION
**Pull request by k88hudson**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/537)

### CODE REVIEW

**Comment by k88hudson** [comment]
cc @nchapman

**Comment by nchapman** [comment]
This worked great. I'll leave it to @rlr to review the code, but the functionality is :+1:

**Comment by rlr** [comment]
oh, I hadn't checked out this page yet. Awesomesauce 🏆 🚀 R+

**Pull request merged**
