### PR TITLE
fix(addon): #174 Fix this this issue

### LINKED ISSUE #174: this._addHiddenURLsTo is not a function
When I create an xpi with `npm run package`, if I try to run it in Nightly (47.0a1), I get the following error on a new tab page:

```
NS_ERROR_MALFORMED_URI:  DOMUtils.js:37:0
TypeError: this._addHiddenURLsTo is not a function ActivityStreams.js:239:13
```

The `Timeline` page works fine.

Both pages work fine on Beta.

### PR DESCRIPTION
**Pull request by rlr**
I love this!

R? @k88hudson @oyiptong 

Fixes #174

### CODE REVIEW

**Comment by oyiptong** [comment]
r+ with a fix to line 279: https://github.com/rlr/activity-streams/blob/cd41cedb8e01607ff0c883e7594ef98b319a959f/lib/ActivityStreams.js#L279:

```javascript
Services.ww.unregisterNotification(this._windowObserver);
```

We need to unregister the observer as well as delete the `_cachedWindowObserver` property in the `unload` method.

**Comment by rlr** [comment]
karma tests failed on the fix/squash/rebase. I didnt change anything that should affect karma tests. restarting travis to see if it was a blip

**Comment by rlr** [comment]
(all tests pass locally)

**Comment by oyiptong** [comment]
That's another issue with Travis, unfortunately. It doesn't keep the old build information: that gets clobbered.

The only way to keep build artifacts is to cause a new build version.

**Comment by rlr** [comment]
travis happy now. :dancer: merging

**Pull request merged**
