### PR TITLE
fix (addon): #460, #467 fix for tab restore

### LINKED ISSUE #460: Bug 1258973 - History is not displayed in new tab & timeline when restarting FF with "Show my windows and tabs from last time" option set
via https://bugzilla.mozilla.org/show_bug.cgi?id=1258973

---

Created attachment 8733775 [details]
No history display after restart.png

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.3
- Activity Stream 1.0.4

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.4) was previously installed on a profile.  

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Navigate to a couple of pages in order to have some history stored.
3. Open the FF options page.
4. Change "When Firefox starts" option into "Show my windows and tabs from last time".
5. Open two new tabs, and in one of them open the "Activity Stream Timeline" page.
6. Wait for the pages to display the stored history and after close the browser.
7. Restart the browser with the same profile and observe both the opened pages .

#### [Expected results]:
The previously stored history is correctly displayed on both pages.

#### [Actual results]:
Both the pages have no history displayed, just the empty placeholders and activity areas (see attached screenshot).

### LINKED ISSUE #467: Bug 1262094 - Activity Stream Timeline content is not displayed after a closed tab was restored
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262094

---

Created attachment 8738080 [details]
Timeline without content.zip

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a profile.
- Have more websites in "Just now" area from Activity Stream Timeline.
- At least 2 tabs are opened in browser

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Click on a link from a website in Timeline.
4. Close the tab.
5. Undo the closed tab.
6. Click on "Back" button.

#### [Expected results]:
The Activity Stream Timeline content is displayed.

#### [Actual results]:
The Activity Stream Timeline content is not shown, only empty placeholders are displayed.

#### [Notes]:
This issue is reproducible also in New Tab page.

### PR DESCRIPTION
**Pull request by rlr**
r? @oyiptong 

oy. Let me know about my attempt to test this :eyes:

Fixes #460 
Fixes #467 

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/514)

### CODE REVIEW

**Comment by rlr** [comment]
well. travis didnt like it :cry:

**Comment by rlr** [comment]
turns out I did something in that test that works on nightly but not on beta... oh well. back at it tomorrow.

**Comment by rlr** [comment]
@oyiptong finally got the tests to pass on beta. I don't really like the hacks I had to put in but they worked 😆 .  Seems like there are some race conditions... Any better ideas? The test fails without the fix so it seems to be testing the right thing.

R?

**Comment by oyiptong** [comment]
r+

**Comment by oyiptong** [comment]
we'll have to see if there are some notifications we can take advantage of. If you haven't found one, then maybe it's best to go ahead with this hack.

However, this is brittle and may fail on other platforms and makes tests go slower. I'd file a separate issue to track this, but let's let it go for now.

**Comment by oyiptong** [comment]
actually, can you see if you can use this?

https://dxr.mozilla.org/mozilla-central/source/browser/components/sessionstore/SessionStore.jsm#72

**Comment by oyiptong** [comment]
you may need to add a listener to the tab object

**Comment by oyiptong** [comment]
can you give it a shot before we make the final call on this?

**Comment by rlr** [comment]
I tried the following but no luck 😞 

```
...

let mm = tab.linkedBrowser.messageManager;

// Close the tab.
yield promiseRemoveTab(tab);

...
tab = yield new Promise(resolve => {
  let t;
  mm.addMessageListener("SessionStore:restoreTabContentComplete", function onMessage(msg) {
    resolve(t);
  });
});
t = SessionStore.undoCloseTab(browserWindow);

...

```

**Comment by oyiptong** [comment]
i think the listener needs to be on the tab. can you catch the tab creation event? you'd need to insert the listener as it's created and before the restore is complete

**Comment by rlr** [comment]
HACKS GONE! I'll merge once travis gives me the green 🚥

**Comment by oyiptong** [comment]
awesome stuff!

**Pull request merged**
