### PR TITLE
fix(addon): #468 Prioritize new data in getCachedLinks

### LINKED ISSUE #468: Bug 1262125 - The bookmarked websites are not displayed with bookmarked status and icon in “Activity Stream Timeline” and “New Tab” page
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262125

---

Created attachment 8738122 [details]
bookmarked websites are not displayed.mp4

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a profile.
- Have at least one website in "Highlights" area from Activity Stream Timeline.
- Multiple pages were previously visited in order to have items displayed in all areas of both “Timeline” and “New Tab” pages. 

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Click on a link from a website in Timeline.
4. Bookmark this page.
5. Return to Activity Stream Timeline.
6. Observe how the bookmarked page is displayed in “Highlights” and “Just now” areas.
7. Navigate to “Bookmarks” tab from Timeline page and observe the recently bookmarked page.

#### [Expected results]:
6\. The website that was bookmarked has a blue star in front of the favicon in the "Just now" area. In the "Highlights" area the status of the item was changed to "Bookmarked x seconds/minutes ago".
7\. The bookmarked website is correctly displayed in “Bookmarks” tab.

#### [Actual results]:
6\. The website that was bookmarked has no blue star in front of the favicon in the "Just now" area. And also the status of the page does not change in the "Highlights" area.
7\. The bookmarked website is not displayed in “Bookmarks” tab.

#### [Notes]:
This issue is reproducible also in New Tab page.

### PR DESCRIPTION
**Pull request by k88hudson**
This fixes `getCachedLinks` so that new values in links will be prioritized over cached ones if they are available.

Fixes #468

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/487)

### CODE REVIEW

**Comment by k88hudson** [comment]
@oyiptong or @rlr R?

**Comment by oyiptong** [comment]
Instead of caching the whole link object, we should cache only the embedly proxy results.

At this point: https://github.com/mozilla/activity-streams/blob/bb62bdfa45f546b40bb5d0a511b94242fa87cc6f/lib/PreviewProvider.js#L230

We should remove https://github.com/mozilla/activity-streams/blob/bb62bdfa45f546b40bb5d0a511b94242fa87cc6f/lib/PreviewProvider.js#L238-243

And make the function `getCachedLinks` return all links when the preview proxy is disabled: https://github.com/mozilla/activity-streams/blob/bb62bdfa45f546b40bb5d0a511b94242fa87cc6f/lib/PreviewProvider.js#L168

**Comment by k88hudson** [comment]
@oyiptong ok, I updated the PR with changes to  _asyncFetchAndCache

**Comment by oyiptong** [comment]
r+

**Pull request merged**
