### PR TITLE
feat(content) #45 top sites ui component

### PR DESCRIPTION
**Pull request by rlr**
* I copied then tweaked a bunch of the styles from RNT
* Should I name it Tiles instead of TopSites?
* This is probably missing some needed media queries but it's hard to know until the rest of the components are laid out

r? @k88hudson

### CODE REVIEW

**Comment by rlr** [comment]
^^ the eslint check dislikes the test code... How do I fix that?

**Comment by k88hudson** [comment]
Awesome! Can you add back the content-test to eslint and add the following to `"rules"`:

```
    "react/jsx-uses-react": 1
```

and the following to `"env"`:

```
"mocha": true
```

**Comment by k88hudson** [comment]
R+ after that

**Comment by rlr** [comment]
done :beers:

**Pull request closed without merging**
