### PR TITLE
Instrument user events

### PR DESCRIPTION
**Pull request by k88hudson**
Including clicks, deletes, shares, search, load more

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/465)

### CODE REVIEW

**Comment by k88hudson** [comment]
@mzhilyaev R?

**Comment by mzhilyaev** [comment]
I would like to have one unit test in test-TabTracker.js that verifies receiving a  "user-action-event" notification from TabTracker upon a user event triggered inside newtab page.  Since  addon code never checks for the action type, any user event (click or search) will be sufficient to test integration.

**Comment by k88hudson** [comment]
Filed https://github.com/mozilla/activity-streams/issues/480 for integration tests

**Comment by mzhilyaev** [comment]
So, me and @k88hudson tried around different ways to do the test, and its not easy.
We decided to R+ this branch, and move requests into integration like tests into #480

**Pull request merged**
