### PR TITLE
chore(addon): #89 Move common files to /common, audit jpm files

### LINKED ISSUE #89: Audit the files in the @activity-streams.xpi file
Running `npm run once` I see some errors (see #88), but if I navigate to <resource://activity-streams/> then I seem to get a directory listing of a JAR file XPI.

Not too interesting, but I was a bit surprised that we're bundling .eslintrc and .jscsrc and the test/ directory. Not sure if we need the LICENSE and README.md files (but if not, we could reduce the file by another 22 KB). Maybe we just need to tweak the .jpmignore file a bit to reduce dead code.

index_of_jar_file____var_folders_qc_g_f0szh95k1fzph34rhmf5jw0000gp_t_030adca6-62c7-4ba3-a444-c47e6f29f1ab_extensions__activity-streams_xpi__

### PR DESCRIPTION
**Pull request by k88hudson**
Fixes #89

### CODE REVIEW

**Comment by k88hudson** [comment]
R? @oyiptong and/or @pdehaan

**Comment by oyiptong** [comment]
r+

**Comment by pdehaan** [comment]
Current contents of my local [241KB] **activity-streams-1.0.4.xpi** file:

```
.
├── LICENSE
├── README.md
├── bootstrap.js
├── common
│   ├── ActionManager.js
│   └── action-manager.js
├── data
│   ├── content
│   │   ├── activity-streams.html
│   │   ├── bundle.js
│   │   ├── img
│   │   │   ├── glyph-delete-16.svg
│   │   │   ├── glyph-more-16.svg
│   │   │   ├── glyph-share-16.svg
│   │   │   └── list-icon.svg
│   │   ├── main.css
│   │   └── vendor.bundle.js
│   └── content-bridge.js
├── install.rdf
├── lib
│   ├── ActivityStreams.js
│   ├── AppURLHider.js
│   ├── Memoizer.js
│   ├── PerfMeter.js
│   ├── PlacesProvider.js
│   ├── SearchProvider.js
│   ├── TabTracker.js
│   ├── TelemetrySender.js
│   └── main.js
├── package.json
└── test
    ├── lib
    │   ├── PlacesTestUtils.js
    │   ├── httpd.js
    │   └── utils.js
    ├── resources
    │   ├── activity-streams-places-changes.html
    │   ├── dummy-activitystreams.html
    │   └── dummy-other.html
    ├── test-Memoizer.js
    ├── test-PerfMeter.js
    ├── test-PlacesProvider.js
    ├── test-SearchProvider.js
    ├── test-TabTracker.js
    ├── test-TelemetrySender.js
    ├── test-awesomebar-empty.js
    ├── test-caching.js
    ├── test-httpd.js
    ├── test-message-passing.js
    └── test-workers.js

8 directories, 43 files
```

**Comment by oyiptong** [comment]
oh hmm... test shouldn't be there. we could shave off 244KB uncompressed

**Comment by oyiptong** [comment]
vendor.bundle.js i assume is the biggest contributor to the uncompressed disk usage?

**Comment by oyiptong** [comment]
```
260K    ./data/content/bundle.js
324K    ./data/content/vendor.bundle.js
```
30% difference... hmmm. this is the product of running `npm run package`

**Pull request merged**
