### PR TITLE
fix(content): #388 Rename Featured to Highlights

### LINKED ISSUE #388: Rename Featured to Highlights
So it sounds a bit less "sponsored" and more personalized.

screenshot_3_29_16__5_30_pm

### PR DESCRIPTION
**Pull request by nchapman**
I managed to get this wrong the last time. Apologies. Spotlight -> Featured -> Highlights :tada: 

Fixes #388.

@pdehaan r?

### CODE REVIEW

**Comment by pdehaan** [comment]
I'll give this a quick test locally to make sure everything looks kosher on bookmarks+timeline+newtab.

**Comment by pdehaan** [comment]
:+1: @nchapman, you've outdone yourself!

activity_stream

**Comment by tspurway** [comment]
LOLZ!!

**Comment by nchapman** [comment]
> :+1: @nchapman, you've outdone yourself!

I've written some code in my day, but none of it makes me as proud as this PR. Thank you for noticing.

**Pull request merged**
