### PR TITLE
fix (addon): #579 hide simple prefs

### LINKED ISSUE #579: hide checkboxes and urls in about:addons prefs
This was discussed to leave or hide checkboxes and urls in addon prefs

screen shot 2016-04-26 at 2 00 01 pm

### PR DESCRIPTION
**Pull request by rlr**
r? @oyiptong 

Fixes #579

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/624)

### CODE REVIEW

**Comment by rlr** [comment]
Here is the new prefs screen with this commit:

screen shot 2016-05-03 at 4 16 17 pm

**Comment by oyiptong** [comment]
Do we want to hide all of them?

I'm good either way, because as a developer I know how to hide prefs. However, as an end-user, it's not Firefox-like to not provide options for users.

**Comment by rlr** [comment]
Just following what the issue says. IMO they shouldnt be preferences if nobody can change them. not sure what the point is.

**Comment by oyiptong** [comment]
following from #579:

We should:
* hide query caching checkbox
* leave preview checkbox as-is
* leave perf logging checkbox as-is

**Comment by rlr** [comment]
OK, ^^ updated to only add query caching to the hidden list.

**Pull request closed without merging**
