### PR TITLE
chore(package): Add Test Pilot link in package description

### LINKED ISSUE #622: Add reference to testpilot.firefox.com in addon meta
We have to add something to the `about:addons` page that 

1. Links back to https://testpilot.firefox.com.
2. Identifies this a Test Pilot experiment.

Exact specifications provided by @nchapman, @johngruen 

Note: this is a blocker for launch.

### PR DESCRIPTION
**Pull request by pdehaan**
r? @oyiptong

### Screenshot:

add-ons_manager

Fixes #622

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/628)

### CODE REVIEW

**Comment by pdehaan** [comment]
No doubt this will 💥 with #624, so we can merge that first then I can rebase.

**Comment by oyiptong** [comment]
Haha. I made the same patch in a local repo.

How about you add a `\n` between the two sentences?

**Comment by oyiptong** [comment]
r+

**Comment by oyiptong** [comment]
The `\n` would ensure that the test-pilot text stands out.

Either way is fine for me.

**Pull request merged**
