### PR TITLE
fix(addon): #625 Renaming ping attributes for bookmarks and history counts

### LINKED ISSUE #625: Missing total_history_size and total_bookmarks in the telemetry.
We have to make sure these have been sent by the addon, and processed by infernyx.

@k88hudson @emtwo

### PR DESCRIPTION
**Pull request by emtwo**
Fixes #625 

This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/636)

### CODE REVIEW

**Comment by emtwo** [comment]
Looks like the only problem was just the name of the attributes!

r? @k88hudson

**Comment by oyiptong** [comment]
@ncloudioj do those attributes correspond to what you're expecting?

**Comment by ncloudioj** [comment]
Yes. @emtwo has confirmed that with me.

**Comment by k88hudson** [comment]
Awesome 👍

**Pull request merged**
