### PR TITLE
chore(lint): Disable ESLint 'no-shadow' and 'no-warning-comments' rules

### LINKED ISSUE #281: Disable the `no-warning-comments` and `no-shadow` ESLint rules for now
They're cluttering up the Travis logs and should reduce us from 13 warnings down to 0 warnings.

Ref: https://github.com/mozilla/activity-streams/pull/279#discussion_r55437162

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #281

### CODE REVIEW

**Comment by pdehaan** [comment]
So quiet!

> activity-streams@1.0.2 test:lint /home/travis/build/mozilla/activity-streams
> eslint . && jscs . && sass-lint -v -q
>
> activity-streams@1.0.2 travis:jpm /home/travis/build/mozilla/activity-streams
> jpm test -b $JPM_FIREFOX_BINARY -v

**Comment by pdehaan** [comment]
Per https://github.com/mozilla/activity-streams/pull/278#discussion_r55859555, not sure if we also want to toggle on the `object-shorthand` rule. Or we can do that in a future PR.

**Comment by k88hudson** [comment]
Looks good to me!

**Pull request merged**
